// This file is generated by the createTypes script.

declare module "sap/ui/geomap/GeomapControlPosition" {
	import {GeomapControlPosition} from "sap/ui/geomap/library";

	/**
	 * Enumeration of the <code>position</code> property of the Geomap controls
	 * 
	 * This enum is part of the 'sap/ui/geomap/library' module export and must be accessed by the property 'GeomapControlPosition'.
	 *
	 * @experimental (since 1.142)
	 * @restricted
	*/
	export default GeomapControlPosition;
}
