name: End-To-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# No permissions are required for this workflow
permissions: {}

jobs:
  e2e:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Use Node.js 22.20.0
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.20.0

    - name: Install dependencies
      run: npm ci

    - name: Run e2e tests
      run: npm run e2e
